### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by yyj142857** [jiangnanboy/movie_kg#1]
运行时候存在问题，百度了很久，实在不知道怎么改了，希望大牛帮忙解决一下，麻烦您了
显示的是这里报错
    private static void initSparkConf() {
        sparkConf = new SparkConf()
                .setAppName("ProcessData")
                .setMaster("local[*]")
                .set("spark.executor.memory", "4g")
                .set("spark.network.timeout", "1000")
                .set("spark.sql.broadcastTimeout", "2000")
                .set("spark.executor.heartbeatInterval", "100");
    }
报错内容：
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.spark.unsafe.array.ByteArrayMethods.<clinit>(ByteArrayMethods.java:54)
	at org.apache.spark.internal.config.package$.<init>(package.scala:1006)
	at org.apache.spark.internal.config.package$.<clinit>(package.scala)
	at org.apache.spark.SparkConf$.<init>(SparkConf.scala:639)
	at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala)
	at org.apache.spark.SparkConf.set(SparkConf.scala:94)
	at org.apache.spark.SparkConf.set(SparkConf.scala:83)
	at org.apache.spark.SparkConf.setAppName(SparkConf.scala:120)
	at com.sy.util.InitSparkSession.initSparkConf(InitSparkSession.java:18)
	at com.sy.util.InitSparkSession.initSparkSession(InitSparkSession.java:28)
	at com.sy.util.InitSparkSession.getSparkSession(InitSparkSession.java:47)
	at com.sy.mainclass.MovieQA.main(MovieQA.java:33)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @49b0b76
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:56)
	... 12 more

**Comment by jiangnanboy** [comment]
查看你的jdk版本问题呢
